apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "ryan-test.example.com"
webhooks:
  - name: "pod-policy.example.com"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "Namespaced"
    clientConfig:
      service:
        path: "/validate"
        namespace: "tgrccloudsecurity"
        name: "validator"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURTRENDQWpBQ0NRQ24xTkdFUm55WDN6QU5CZ2txaGtpRzl3MEJBUXNGQURCbU1Rc3dDUVlEVlFRR0V3SlYKVXpFTE1Ba0dBMVVFQ0F3Q1UwTXhFekFSQmdOVkJBY01Da05vWVhKc1pYTjBiMjR4RURBT0JnTlZCQW9NQjBOaApjbWRwYkd3eEl6QWhCZ05WQkFNTUduSnZiM1F1ZEdkeVkyTnNiM1ZrYzJWamRYSnBkSGt1YzNaak1CNFhEVEl4Ck1EVXlOREU1TlRJeU1sb1hEVEkyTURVeU16RTVOVEl5TWxvd1pqRUxNQWtHQTFVRUJoTUNWVk14Q3pBSkJnTlYKQkFnTUFsTkRNUk13RVFZRFZRUUhEQXBEYUdGeWJHVnpkRzl1TVJBd0RnWURWUVFLREFkRFlYSm5hV3hzTVNNdwpJUVlEVlFRRERCcHliMjkwTG5SbmNtTmpiRzkxWkhObFkzVnlhWFI1TG5OMll6Q0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOV3AyVjdINE04T0FCK1ZheTgrR3ZDUFF4UEtqUC8rcktaMVY5bTkKcEZoRmhQcURabGtqdEc3angzVXFYYnpRZ2tCejEvRVEzdjVmSFlieEVCK0dJbFFXQThMU3B5SWd5L2VoSGl2RgozTzVhN3UwemtUZ0dTS3BNajJ0T3ZDRkJBQ29UM2ZVSmdSN3luT3krVW4zOEpadzBmWWt4NGg5c0NVTisxWk11CnlneWRxdTFJYkgwbldjUE1xRHFqdlB3WXZPSkR3VEs2VncxZVVhWFFpS1JmQUdpaE45REJaRjNTV3hRMWkveFkKRmFkTVkrdTBDbUFyckhiQVdTb3Z0cmhSL25ZVk5JT3U3ZE9vcitOTHZIbmhuTVF3MDJMcUhLSjNjbVZTMVRvYQpFS1NxdVN0WlEwSS9hRDlUcEJkZnZPRFFlR3BsOEY0cnpVb0E1QXYxS1NFc3JPMENBd0VBQVRBTkJna3Foa2lHCjl3MEJBUXNGQUFPQ0FRRUFQcW9GamdBcUdrN21XaFVCS3c3eXNFbTlDZFFON1FnQzhHQzlIaXoxaWFnenNWaCsKL0xFdVFONWVzMkRFd1NaWnZQT0lFTUtuMEVJVllkdGhDYTRGcVNyNC9NOWJBcEE4V0svMHZEOXBWWld5d0g0OQpIanlib0swaFl5VUdrczM4RStnM3NERTd4bXZIOGdqMFpEZCtOTFkwSDMrVzE1RXNvby9DbjJtZllOUitIY1d5CkFodldzM0hLTWxTQlpvK3IzZngyRlhkR1NwYXljNGd2cHMyTkRXemRUNllBYUdJZmJXUzFVdUFrd2N5WDBpU2MKNittYk1JeEZ0dGZzdXVhUjV2eEliakNQdyt6VVE2emkwYk5sY01FaThUSi8wSTMrVEJrZ1I0YVVnV3d5M21OagpOZlpjRXpQR2VETnZ0dFhZdTNVT3BUbDdvQWMvYlpuNWJTazlzUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
